apiVersion: v2
type: application
name: vault-secrets-reloader-namespaced
version: 0.0.0
appVersion: latest
description: A Kubernetes Controller that reloads workloads on a referenced secret change in HashiCorp Vault.
keywords:
  - vault
  - hashicorp
  - secret
  - webhook
  - reloader
home: https://bank-vaults.dev
sources:
  - https://github.com/hashicorp/vault
  - https://github.com/davealmr/vault-secrets-reloader-namespaced
maintainers:
  - name: Bank Vaults Maintainers
    email: team@bank-vaults.dev
